---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# hitop

<!-- badges: start -->
<!-- badges: end -->

The goal of hitop is to provide functions helpful for researchers working on the Hierarchical Taxonomy of Psychopathology (HiTOP).

## Installation

You can install the development version of hitop from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("jmgirard/hitop")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(hitop)

## Score simulated PID-5 data
data("sim_pid5")
score_pid5(sim_pid5, tibble = TRUE)
validity_pid5(sim_pid5, tibble = TRUE)

## Score simulated PID-5-FSF data
data("sim_pid5fsf")
score_pid5fsf(sim_pid5fsf, tibble = TRUE)
validity_pid5fsf(sim_pid5fsf, tibble = TRUE)

## Score real PID-5-FSF data
data("ku_pid5fsf")
score_pid5fsf(ku_pid5fsf, id = "response_id", tibble = TRUE)
validity_pid5fsf(ku_pid5fsf, id = "response_id", tibble = TRUE)
```
